###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 500
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: True
  TRAIN_PS: 128
  VAL_PS: 112
  TRAIN_DIR: '/media/sr4/43cec1a8-a7e3-4f24-9dbb-b9b1b6950cf1/yjt/zhuanhaun/dataset/train/syn+real'       # path to training data
  VAL_DIR: '/media/sr4/43cec1a8-a7e3-4f24-9dbb-b9b1b6950cf1/yjt/zhuanhaun/dataset/test' # path to validation data
  SAVE_DIR: '/home/sr4/yjt1/tip_checkpoint/checkpoint_no_fft2/'           # path to save models and images
  # SAVE_IMAGES: False



